project_id = "ayyklhshzzfkutkrpipj"

[functions.cnpj-lookup]
verify_jwt = false

[functions.render-cnpj]
verify_jwt = false

[functions.populate-cnpj-cache]
verify_jwt = false

[functions.empresa-search]
verify_jwt = false